# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - achievers-admin

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18.x"

  #     - name: npm install and test
  #       run: |
  #         npm install
  #         npm run test
  #         npm run build

  #     - name: run migrations
  #       run: |
  #         npm run setup

  #     - name: prune for prod
  #       run: |
  #         npm install --omit=dev

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: node-app
  #         path: |
  #           node_modules
  #           build
  #           public
  #           package.json
  #           prisma
  #           !prisma/BaltimoreCyberTrustRoot.*

  # build:
  #   name: ğŸ³ Build
  #   # only build/deploy main branch on pushes
  #   # if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ğŸ›‘ Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.9.1

  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v3

  #     - name: ğŸ‹ Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: ${{ secrets.AZURE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=pr
  #           type=semver,pattern={{version}}
  #           type=semver,pattern={{major}}.{{minor}}
  #           type=sha,format=long,prefix=
  #     - name: ğŸ”“ ACR authentication
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: ${{ secrets.AZURE_REGISTRY_URL }}
  #         username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  #         password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  #     - name: ğŸ‹ Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: src
  #         file: Dockerfile
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: duvet86/achievers-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: ğŸš€ Deploy
    runs-on: ubuntu-latest
    # needs: [lint, typecheck, vitest, cypress, build]
    # only build/deploy main branch on pushes
    # if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ğŸ”“ Azure authentication
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ğŸš€ Deploy to Azure WebApp (production)
        uses: azure/webapps-deploy@v2
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          app-name: "achievers-admin"
          images: duvet86/achievers-app:latest
